[project]
name = "pythia"
version = "0.1.0.dev0"
description = "approx oracle"
authors = [
    { name = "Peter Jin" }
]
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
web = [
    # "fastapi[standard]==0.116.1",
    "fastapi[standard]==0.115.14",
    "uvicorn[standard]==0.34.3",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "pythia",
]

[tool.ruff.lint]
ignore = ["F541"]
