[project]
name = "pythia"
version = "0.1.0.dev0"
description = "(auto)pythia"
authors = [
    { name = "Peter Jin" },
    { name = "autopythia" },
]
license = { text = "Apache-2.0" }
requires-python = ">=3.9"
dependencies = []

# [project.optional-dependencies]
# web = [
#     "fastapi[standard]==0.115.14",
#     "uvicorn[standard]==0.34.3",
# ]

[project.scripts]
autopythia = "pythia.auto:_main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "pythia",
    "pythia.*",
]

[tool.ruff.lint]
ignore = ["F541"]
